### ISSUE TITLE
`make mock-gen` failed

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/finality-gadget#28]
```
$ make mock-gen                                                    [12:02:00]
go install go.uber.org/mock/mockgen@latest
mockgen -source=db/interface.go -package mocks -destination ./testutil/mocks/db_mock.go
make: *** [mock-gen] Killed: 9
```

we should also add this to CI to
- run it
- check if there is any diff generated

**Comment by parketh** [comment]
i tried on latest `main` branch and it works 

<img width="944" alt="image" src="https://github.com/user-attachments/assets/3dc5c302-65b5-4f4c-8cf5-6a5f7e0de6ef">

maybe reinstalling mockgen / cleaning cache helps? `Killed: 9` seems to be a Mac Silicon issue, some relevant discussion here: https://apple.stackexchange.com/questions/258623/how-to-fix-killed-9-error-in-mac-os

**Comment by bap2pecs** [comment]
this is not easy to fix. submitted issue: https://github.com/uber-go/mock/issues/211

also tried to change back to the old archived repo `go install github.com/golang/mock/mockgen@latest` but test will fail

so I will just leave it for now
