### ISSUE TITLE
Refactor: make Babylon chain RPC a config instead of using switch

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/finality-gadget#4]
**[<img src="https://avatars.githubusercontent.com/u/111917526?s=17&v=4" width="17" height="17"> @bap2pecs](https://github.com/bap2pecs)** cloned issue [babylonchain/babylon-finality-gadget#35](https://github.com/babylonchain/babylon-finality-gadget/issues/35) on 2024-06-26: 

> ## Summary
> 
> 
> 
> https://github.com/babylonchain/babylon-da-sdk/pull/30#discussion_r1653779473
> 
> 
> 
> ## Tasks
> 
> 
> 
> - [x] add it to the client config struct
> 
> - [x] modify in the FP and OP repos accordingly

**Comment by lesterli** [comment]
Added [ChainID and RPCAddress](https://github.com/babylonlabs-io/finality-gadget/blob/main/config/config.go#L15-L16) config items for Babylon.
